build.gradle
src/main/java/weavers/siltarae/global/config/SwaggerConfig.java

Swagger 초기 세팅

---

build.gradle

Issue: close #11 
lombok Gradle 변경

type:[#11] lombok Gradle 변경

---

src/main/java/weavers/siltarae/user/domain/repository/UserRepository.java

feat: [#13] 테스트 사용자 조회를 위한 Repository 추가

---

src/main/java/weavers/siltarae/tag/domain/Tag.java

close #17
- 모델명을 Category에서 Tag로 변경
- 패키지명을 category에서 tag로 변경

refactor: Category의 모델명을 Tag로 수정

---

build.gradle
src/main/java/weavers/siltarae/tag/domain/Tag.java
src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java

#4 
검증 관련 gradle 설정을 추가하고, 태그 도메인 파트를 구현했습니다.

feat: [#4] 태그 도메인 구현

---

build.gradle
src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
src/main/java/weavers/siltarae/mistake/controller/MistakeController.java
src/main/java/weavers/siltarae/mistake/domain/Mistake.java
src/main/java/weavers/siltarae/mistake/domain/repository/MistakeRepository.java
src/main/java/weavers/siltarae/mistake/dto/request/MistakeCreateRequest.java
src/main/java/weavers/siltarae/mistake/service/MistakeService.java
src/main/java/weavers/siltarae/tag/domain/Tag.java
src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java
src/main/java/weavers/siltarae/user/domain/User.java
src/test/java/weavers/siltarae/mistake/service/MistakeServiceTest.java

Issue: close #5 
- 실수 도메인 작성
- 실수 비즈니스 로직 작성
- User 모델 작성

feat: [#5] 실수 생성 기능 구현

---

src/main/java/weavers/siltarae/global/exception/GlobalExceptionHandler.java

close #10 
GlobalExceptionHandler 로 오타 수정

chore: [#10] GlobalExceptionHandler 파일명 오타 수정

---

src/main/java/weavers/siltarae/mistake/dto/request/MistakeCreateRequest.java

issue: #5 
- 실수 생성 Request import 누락 부분 추가

fix: [#5] 실수 생성 import 누락 추가

---

.github/workflows/CD.yml

deploy: 배포 CD, GitHub 액션 설정

---

.github/workflows/CD.yml

Issue: #26 
- resources 폴더 생성 스크립트 추가

deploy: resources 폴더 생성 스크립트 추가

---

Dockerfile-prod

deploy: dockerFile 추가

---

.github/workflows/CD.yml

deploy: gradle caching 추가

---

Dockerfile-prod

Issue: #26 
- siltarae 로 jar 파일명 변경

deploy: siltarae 로 jar 파일명 변경

---

src/main/java/weavers/siltarae/tag/domain/Tag.java

Issue: #42 
- User 엔티티명을 Member 로 변경 중에 user_id 로 구현되어있는 부분을 member_id 로 변경

fix: User 엔티티명을 Member로 변경 - user_id -> member_id

---

src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
src/main/java/weavers/siltarae/tag/dto/response/TagResponse.java

Issue: #46 #48 
- 브랜치 간의 marge 시 코드 충돌 및 에러 해결

BUG: 브랜치 marge 시 충돌 해결

---

.github/workflows/CD.yml

Issue: #46 
- GitHub Actions resources 폴더 진입 스크립트 추가로 application.yml 파일을 재생성

fix: resources 폴더 진입 스크립트 추가

---

src/main/java/weavers/siltarae/mistake/controller/MistakeController.java

Issue: close #53 
- 실수 API 경로 수정

fix:[#53] API 경로 수정

---

build.gradle
src/main/java/weavers/siltarae/global/config/QueryDslConfig.java

Issue: close #60 
- QueryDsl Gradle 설정 추가

chore:[#60]  QueryDsl Gradle 설정 추가

---

src/main/java/weavers/siltarae/global/BaseEntity.java
src/main/java/weavers/siltarae/global/CreateTimeEntity.java
src/main/java/weavers/siltarae/global/CreatedAt.java
src/main/java/weavers/siltarae/like/controller/LikeController.java
src/main/java/weavers/siltarae/like/domain/LikeId.java
src/main/java/weavers/siltarae/like/domain/Likes.java
src/main/java/weavers/siltarae/like/domain/repository/LikeRepository.java
src/main/java/weavers/siltarae/like/service/LikeService.java
src/main/java/weavers/siltarae/mistake/domain/Mistake.java

Issue:  #56 
- 좋아요 도메인 작성
- 좋아요 등록, 삭제 Service 구현
충돌이 날 수 있으며 develop 에 모든 코드가 올라간다면 에러가 나지 않습니다.

feat:[#56] 좋아요 기능 개발

---

src/main/java/weavers/siltarae/comment/controller/CommentController.java
src/main/java/weavers/siltarae/comment/domain/Comment.java
src/main/java/weavers/siltarae/comment/domain/repository/CommentRepository.java
src/main/java/weavers/siltarae/comment/dto/request/CommentCreateRequest.java
src/main/java/weavers/siltarae/comment/dto/request/CommentListRequest.java
src/main/java/weavers/siltarae/comment/dto/response/CommentListResponse.java
src/main/java/weavers/siltarae/comment/dto/response/CommentResponse.java
src/main/java/weavers/siltarae/comment/service/CommentService.java
src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
src/main/java/weavers/siltarae/mistake/domain/Mistake.java
src/main/java/weavers/siltarae/mistake/domain/repository/MistakeRepository.java

Issue: #57 
- 댓글 도메인 작성
- 댓글 관련 Dto 작성
- 댓글 등록, 조회, 삭제 기능 구현
- Mistake 와 Comment 연관관계 구성

feat:[#57] 댓글 관련 기능 구현

---

src/main/java/weavers/siltarae/comment/service/CommentService.java
src/main/java/weavers/siltarae/like/service/LikeService.java

Issue: close #71 
- ErrorCode 가 NOT_FOUND_USER 에서 NOT_FOUND_MEMBER 로 변경

fix:[#71] 에러코드 변경

---

src/main/java/weavers/siltarae/mistake/dto/response/FeedResponse.java
src/main/java/weavers/siltarae/mistake/dto/response/MistakeResponse.java

Issue: #65 
- 좋아요 댓글 구현에 맞추어 좋아요, 댓글 개수 반환
- memberId, memberName 추가

feat: [#65]좋아요, 댓글 개수 반환 & memberId, memberName 추가

---

src/main/java/weavers/siltarae/comment/dto/request/CommentListRequest.java
src/main/java/weavers/siltarae/global/dto/request/PageRequest.java
src/main/java/weavers/siltarae/mistake/controller/MistakeController.java
src/main/java/weavers/siltarae/mistake/dto/request/FeedRequest.java

Issue: #69 
- 페이징처리에 필요한 PageRequst Dto 생성
- 페이징처리 Dto 에 상속

refactor:[#69] 페이징 처리에 필요한 RequestDto 통합

---

src/main/java/weavers/siltarae/global/config/SwaggerConfig.java

Issue: #80 
- SwaggerUi Server List 추가

fix: [#80] SwaggerUi ServerList 백엔드 도메인 추가

---

src/main/java/weavers/siltarae/global/config/CorsConfig.java

close #79 
- CORS 이슈 해결을 위해 WebMvcConfigurer 이용
- http://localhost:3000에서 오는 요청을 허용

fix: [#79] CORS 정책 설정

---

src/main/java/weavers/siltarae/comment/controller/CommentController.java
src/main/java/weavers/siltarae/like/controller/LikeController.java
src/main/java/weavers/siltarae/login/controller/LoginController.java
src/main/java/weavers/siltarae/mistake/controller/MistakeController.java
src/main/java/weavers/siltarae/tag/controller/TagController.java
src/main/java/weavers/siltarae/tag/service/TagService.java
src/test/java/weavers/siltarae/tag/TagTestFixture.java
src/test/java/weavers/siltarae/tag/service/TagServiceTest.java

close #89 
- TagFixture에 `List.of()` 대신 `Arrays.asList()`로 만든 mistakes 리스트를 넣어주었습니다.

fix: [#89]태그 삭제 테스트 관련 버그 수정

---

src/main/java/weavers/siltarae/comment/controller/CommentController.java
src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
src/main/java/weavers/siltarae/like/controller/LikeController.java
src/main/java/weavers/siltarae/login/AccessTokenExtractor.java
src/main/java/weavers/siltarae/login/Auth.java
src/main/java/weavers/siltarae/login/AuthArgumentResolver.java
src/main/java/weavers/siltarae/login/controller/LoginController.java
src/main/java/weavers/siltarae/login/service/LoginService.java
src/main/java/weavers/siltarae/mistake/controller/MistakeController.java
src/main/java/weavers/siltarae/tag/controller/TagController.java
src/main/java/weavers/siltarae/tag/service/TagService.java
src/test/java/weavers/siltarae/tag/TagTestFixture.java
src/test/java/weavers/siltarae/tag/service/TagServiceTest.java

Issue: #85 #86 #89 #92 #93 
- 인증관련 내용 추가
- Redis 설정 추가
- 오류 발생 수정

Deploy: 백엔드 1차스크립트 오류 & 수정사항 배포

---

src/main/java/weavers/siltarae/member/controller/MemberController.java
src/main/java/weavers/siltarae/member/domain/Member.java
src/main/java/weavers/siltarae/member/service/MemberService.java

Issue: #98 
- 회원 탈퇴 기능 추가
- 설정파일 변경

Deploy: 백엔드 1차스크립트 설정파일변경 & 기능 추가 배포

---

src/main/java/weavers/siltarae/global/config/AuthConfig.java

close #100 
- AuthArgumentResolver를 등록하였습니다.

fix: [#100] 액세스 토큰 파싱 오류 수정

---

src/main/java/weavers/siltarae/mistake/controller/MistakeController.java
src/main/java/weavers/siltarae/mistake/domain/repository/MistakeRepository.java
src/main/java/weavers/siltarae/mistake/dto/request/MistakeListRequest.java
src/main/java/weavers/siltarae/mistake/dto/response/MistakeListResponse.java
src/main/java/weavers/siltarae/mistake/service/MistakeService.java

Issue: #97 
- mistake 정보에 Tag 정보까지 포함해서 데이터 보내기

feat: [#97] 나의 실수 리스트 조회에서 태그 리스트 조건 추가

---

src/main/java/weavers/siltarae/member/controller/MemberController.java
src/main/java/weavers/siltarae/member/domain/Member.java
src/main/java/weavers/siltarae/member/domain/repository/MemberRepository.java
src/main/java/weavers/siltarae/member/dto/MemberResponse.java
src/main/java/weavers/siltarae/member/dto/MemberUpdateRequest.java
src/main/java/weavers/siltarae/member/service/MemberService.java

close #94 
- 회원 닉네임 수정 기능을 구현하였습니다.

feat: [#94]닉네임 수정 기능 구현

---

build.gradle
src/main/java/weavers/siltarae/global/config/S3Config.java
src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
src/main/java/weavers/siltarae/global/image/ImageUtil.java
src/main/java/weavers/siltarae/global/image/domain/Image.java
src/main/java/weavers/siltarae/member/controller/MemberController.java
src/main/java/weavers/siltarae/member/domain/Member.java
src/main/java/weavers/siltarae/member/service/MemberService.java

close #112 
- 프로필 이미지 업로드 기능을 추가했어요.
- 이미지 업로드 시, 기존 이미지는 즉시 삭제됩니다.
- 디폴트 이미지는 `default_image.png`로 설정됩니다.

feat: [#112] 프로필 이미지 업로드 기능 구현

---

build.gradle
src/main/java/weavers/siltarae/global/config/AuthConfig.java
src/main/java/weavers/siltarae/global/config/S3Config.java
src/main/java/weavers/siltarae/global/exception/AuthException.java
src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
src/main/java/weavers/siltarae/global/image/ImageUtil.java
src/main/java/weavers/siltarae/global/image/domain/Image.java
src/main/java/weavers/siltarae/login/AccessTokenExtractor.java
src/main/java/weavers/siltarae/member/controller/MemberController.java
src/main/java/weavers/siltarae/member/domain/Member.java
src/main/java/weavers/siltarae/member/domain/repository/MemberRepository.java
src/main/java/weavers/siltarae/member/dto/MemberResponse.java
src/main/java/weavers/siltarae/member/dto/MemberUpdateRequest.java
src/main/java/weavers/siltarae/member/dto/request/MemberUpdateRequest.java
src/main/java/weavers/siltarae/member/dto/response/MemberInfoResponse.java
src/main/java/weavers/siltarae/member/dto/response/MemberNicknameResponse.java
src/main/java/weavers/siltarae/member/service/MemberService.java
src/main/java/weavers/siltarae/tag/controller/TagController.java
src/main/java/weavers/siltarae/tag/service/TagService.java

Issue: #94 #106 #110 #109 #112 #116 #112 #120 #117 
- 기능 수정 내용 배포

Deploy: 백엔드 1차 스크립트 수정 배포

---

src/main/java/weavers/siltarae/global/image/ImageUtil.java
src/main/java/weavers/siltarae/member/domain/Member.java
src/main/java/weavers/siltarae/member/service/MemberService.java

Deploy: 1차 스크립트 수정 배포

---

src/main/java/weavers/siltarae/global/config/CorsConfig.java
src/main/java/weavers/siltarae/login/AccessTokenExtractor.java

Issue: #120 
- Authorization 헤더를 허용하도록 CORS 설정 변경

fix: [#120]CORS 설정 변경

---

src/main/java/weavers/siltarae/global/config/CorsConfig.java

Issue: #120 
- 토큰 CORS 오류 관련 배포

Deploy: 토큰, Cors 관련 배포

---

src/main/java/weavers/siltarae/mistake/controller/MistakeController.java
src/main/java/weavers/siltarae/mistake/service/MistakeService.java

Issue: #129 
- 피드에서 상세 조회 시 자신의 게시글이 아니여도 조회 가능하게끔 변경

refactor: [#129] 피드에서 상세 조회 가능

---

src/main/java/weavers/siltarae/global/config/CorsConfig.java
src/main/java/weavers/siltarae/mistake/controller/MistakeController.java
src/main/java/weavers/siltarae/mistake/service/MistakeService.java

Issue: #120 #129 
- CORS 변경
- API 수정

Deploy: CORS, API 수정 부분 배포

---

build.gradle

Issue: #122 
- security build.gradle 설정 추가

Setting: [#122] security build.gradle 설정 추가

---

build.gradle

setting: security build.gradle 설정 제거

---

build.gradle

Deploy: 설정파일 & 시큐리티 설정 제거 배포

---

src/main/java/weavers/siltarae/tag/domain/Tag.java

Issue: #141 
- 설정파일 수정
- 오류 수정

Deploy: 설정파일 수정 & 오류 수정 배포

---

src/main/java/weavers/siltarae/comment/controller/CommentController.java
src/main/java/weavers/siltarae/comment/service/CommentService.java

Issue: Close #137 
- 댓글을 작성 시 작성된 댓글의 내용을 Response 로 보내줍니다.

refactor: [#137] 댓글 등록 시 등록된 댓글 Response 추가

---

src/main/java/weavers/siltarae/like/domain/LikeId.java

Issue: #172 
- LikeId 클래스에 직렬화를 추가하였습니다.

fix: [#172] 복합키 키 클래스에 직렬화 기능 추가

---

build.gradle

Issue: #174 
- build.gradle 파일에서 현재 사용하고 있지 않는 QueryDsl 설정을 수정해주었어요.

fix: 현재 사용하지 않는 QueryDsl 설정 수정

---

.github/workflows/CD.yml

Issue: #177 
- 실타래 백엔드 CI/CD 를 자동화 하였습니다!
- 배포 방식이 수정되었어요. 
S3 에는 배포 스크립트가 저장되어있고 GitHubAction 이 이를 이용하여 AWS CodeDeploy 를 발동 시켜서 배포를 하고있어요

deploy: 실타래 CI/CD 자동화 및 배포 방법 수정

---

.github/workflows/CD.yml

Issue: #177 
- main 으로 PR 올렸을때 if(main) 조건이 없어서 PR 만 올려도 배포가 되고있어요 해당 부분을 if(main) 을 추가해서 수정하였습니다.

deploy: [#177] 배포 시 if(main) 조건 추가

---

build.gradle

close #185
- 기존에 사용하던 `org.springframework.cloud` 패키지를 `io.awspring.cloud`로 변경했어요.

setting: [#185] S3 관련 패키지 변경

---

src/main/java/weavers/siltarae/login/controller/LoginController.java
src/main/java/weavers/siltarae/login/domain/TokenProvider.java
src/main/java/weavers/siltarae/login/service/LoginService.java

close #188 
- `LoginService.login()` 메서드를 수정했는데, LoginController에서 해당 메서드를 호출하는 부분을 수정하는 걸 까먹었어요😭

fix: [#188] 수정된 LoginService.login() 메서드에 맞게 호출 시 파라미터 제거

---

src/main/java/weavers/siltarae/login/controller/LoginController.java
src/main/java/weavers/siltarae/login/domain/GoogleProvider.java
src/main/java/weavers/siltarae/login/domain/OAuthProvider.java
src/main/java/weavers/siltarae/login/dto/request/LoginRequest.java
src/main/java/weavers/siltarae/login/service/LoginService.java

close #191 
- 수정 전: 리다이렉트 URI를 yml 파일에서 받아왔어요.
- 수정 후: 리다이렉트 URI를 프론트에서 받아와요.

refactor: [#191] 리다이렉트 URI를 프론트에서 받아오도록 수정

---

build.gradle
src/main/java/weavers/siltarae/global/image/domain/Image.java
src/main/java/weavers/siltarae/login/controller/LoginController.java
src/main/java/weavers/siltarae/login/domain/GoogleProvider.java
src/main/java/weavers/siltarae/login/domain/OAuthProvider.java
src/main/java/weavers/siltarae/login/domain/TokenProvider.java
src/main/java/weavers/siltarae/login/dto/request/LoginRequest.java
src/main/java/weavers/siltarae/login/service/LoginService.java
src/main/java/weavers/siltarae/mistake/domain/repository/MistakeRepository.java
src/main/java/weavers/siltarae/tag/dto/response/TagListResponse.java
src/main/java/weavers/siltarae/tag/dto/response/TagResponse.java
src/main/java/weavers/siltarae/tag/service/TagService.java

deploy: 백엔드 배포

---

src/main/java/weavers/siltarae/login/AuthArgumentResolver.java
src/main/java/weavers/siltarae/login/controller/LoginController.java
src/main/java/weavers/siltarae/login/domain/LoginInfo.java
src/main/java/weavers/siltarae/login/domain/TokenPair.java
src/main/java/weavers/siltarae/login/dto/response/LoginResponse.java
src/main/java/weavers/siltarae/login/infrastructure/GoogleAuthClient.java
src/main/java/weavers/siltarae/login/infrastructure/GoogleProvider.java
src/main/java/weavers/siltarae/login/infrastructure/OAuthProvider.java
src/main/java/weavers/siltarae/login/infrastructure/TokenProvider.java
src/main/java/weavers/siltarae/login/service/LoginService.java
src/main/java/weavers/siltarae/member/service/MemberService.java
src/test/java/weavers/siltarae/global/ControllerTest.java
src/test/java/weavers/siltarae/integration/BaseIntegrationTest.java

Issue: #194 
- 배포합니다.
없으면 생략 가능합니다.

deploy: 백엔드 재배포 
