coding-union-kr/siltarae-be

- src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
- src/main/java/weavers/siltarae/tag/controller/TagController.java
- src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java
- src/main/java/weavers/siltarae/tag/dto/request/TagCreateRequest.java
- src/main/java/weavers/siltarae/tag/service/TagService.java
- src/test/java/weavers/siltarae/tag/TagTestFixture.java
- src/test/java/weavers/siltarae/tag/controller/TagControllerTest.java
- src/test/java/weavers/siltarae/tag/service/TagServiceTest.java
- src/test/java/weavers/siltarae/user/UserTestFixture.java
close #4 
- 태그 등록 API를 구현했습니다.
- 태그 등록 테스트를 구현했습니다.
관련해서 `DUPLICATED_TAG_NAME` 이라는 예외 코드를 추가하였습니다.
- 회원 기능이 아직 구현되지 않아, 임의로 id=1인 유저를 이용하였습니다.
- 테스트에 필요한 데이터를 Fixture로 분리하였습니다.
- 태그명에 공백을 허용할지에 대해 논의가 필요해 보입니다. 현재는 한글, 영어, 숫자, 그리고 언더바만 허용합니다.
> feat: [#4] 태그 등록 기능 구현

- src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java
- src/main/java/weavers/siltarae/tag/service/TagService.java
- src/test/java/weavers/siltarae/tag/service/TagServiceTest.java
close #4 
TagRepository의 `existsByUser_UserIdAndName`을 `existsByUser_IdAndName`으로 수정했습니다.
> bug: [#4] TagRepository 쿼리메서드명 수정

- src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
- src/main/java/weavers/siltarae/mistake/controller/MistakeController.java
- src/main/java/weavers/siltarae/mistake/domain/Mistake.java
- src/main/java/weavers/siltarae/mistake/domain/repository/MistakeRepository.java
- src/main/java/weavers/siltarae/mistake/dto/response/MistakeListResponse.java
- src/main/java/weavers/siltarae/mistake/dto/response/MistakeResponse.java
- src/main/java/weavers/siltarae/mistake/dto/response/TagResponse.java
- src/main/java/weavers/siltarae/mistake/service/MistakeService.java
- src/main/java/weavers/siltarae/tag/controller/TagController.java
- src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java
- src/main/java/weavers/siltarae/tag/dto/request/TagCreateRequest.java
- src/main/java/weavers/siltarae/tag/dto/response/TagResponse.java
- src/main/java/weavers/siltarae/tag/service/TagService.java
- src/test/java/weavers/siltarae/tag/TagTestFixture.java
- src/test/java/weavers/siltarae/tag/controller/TagControllerTest.java
- src/test/java/weavers/siltarae/tag/service/TagServiceTest.java
- src/test/java/weavers/siltarae/user/UserTestFixture.java
Issue: #3 
- 나의 실수 리스트 조회 API 를 구현하였습니다.
- 나의 실수 상세 보기 API 를 구현하였습니다.
- 실수 선택 삭제 API 를 구현하였습니다.
> feat: [#3] 실수 조회, 삭제 기능 구현

- src/main/java/weavers/siltarae/tag/dto/request/TagCreateRequest.java
close #4 
태그명 검증에 아래와 같은 제약조건을 추가하였습니다.
- 언더바 연속 2개 이상 사용 불가
- 태그명은 한글, 숫자, 영어로 시작해야 함
> bug: [#4] 제약조건에 맞게 태그명 검증 수정

- src/main/java/weavers/siltarae/mistake/service/MistakeService.java
close #5 
- 실수 등록 시 검증을 RequestDto 에서 진행하기 때문에 Service 까지 재검증할 필요성이 없다고 생각되어 메소드 삭제
- 기획 회의 상에서 실수 내용에 특수문자를 허용하게끔 했기때문에 해당 내용 메소드 삭제
> feat: [#5] 실수 등록 시 검증 로직 변경 및 실수 내용 특수문자 허용

- src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
- src/main/java/weavers/siltarae/tag/controller/TagController.java
- src/main/java/weavers/siltarae/tag/domain/Tag.java
- src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java
- src/main/java/weavers/siltarae/tag/dto/response/TagListResponse.java
- src/main/java/weavers/siltarae/tag/dto/response/TagResponse.java
- src/main/java/weavers/siltarae/tag/service/TagService.java
- src/test/java/weavers/siltarae/tag/TagTestFixture.java
- src/test/java/weavers/siltarae/tag/controller/TagControllerTest.java
- src/test/java/weavers/siltarae/tag/service/TagServiceTest.java
close #7   
- 태그 목록 조회 API 및 관련 테스트 구현
- 태그 선택 삭제 API 및 관련 테스트 구현
- 태그 삭제 요청 시, 이미 삭제된 태그가 포함되어 있는 경우 3002 `NOT_FOUND_TAG` 예외가 발생합니다.
> feat: [#7] 태그 목록 조회, 선택 삭제 기능 구현

- src/main/java/weavers/siltarae/SiltaraeBeApplication.java
- src/main/java/weavers/siltarae/global/BaseEntity.java
- src/main/java/weavers/siltarae/mistake/domain/Mistake.java
- src/main/java/weavers/siltarae/mistake/service/MistakeService.java
- src/main/java/weavers/siltarae/tag/domain/Tag.java
- src/main/java/weavers/siltarae/tag/service/TagService.java
- src/main/java/weavers/siltarae/user/domain/User.java
- src/test/java/weavers/siltarae/mistake/service/MistakeServiceTest.java
- src/test/java/weavers/siltarae/tag/TagTestFixture.java
- src/test/java/weavers/siltarae/tag/domain/TagTest.java
- src/test/java/weavers/siltarae/tag/service/TagServiceTest.java
- src/test/java/weavers/siltarae/user/UserTestFixture.java
close #9 
- JPA Auditing을 사용하여 엔티티 저장 시 생성일이 자동 등록되도록 하였습니다.
- BaseEntity 클래스를 생성하였습니다.
- 생성일, 삭제일, 삭제 메서드, 삭제 여부 반환 메서드를 멤버로 갖고 있습니다. 
- 기존 엔티티들은 BaseEntity를 상속합니다.
> refactor: [#9] 생성일 자동화

- src/main/java/weavers/siltarae/login/controller/LoginController.java
- src/main/java/weavers/siltarae/login/domain/TokenProvider.java
Issue: #33 
- 로그인 API의 HttpMethod를 GET으로 변경
> fix: 로그인 API의 HttpMethod를 구글 명세서에 맞게 Post에서 Get으로 변경

- src/main/java/weavers/siltarae/SiltaraeBeApplication.java
- src/main/java/weavers/siltarae/global/config/JpaAuditingConfig.java
- src/test/java/weavers/siltarae/tag/TagTestFixture.java
- src/test/java/weavers/siltarae/tag/controller/TagControllerTest.java
close #59 
- JpaAuditing을 설정 클래스로 분리하였습니다.
- TagTestFixture의 mistakes 필드에 값을 넣어주었습니다.
- 특수문자가 포함된 태그를 등록하는 테스트의 예상 메세지를 수정하였습니다.
> fix: [#59] 컨트롤러 테스트 오류 수정

- src/main/java/weavers/siltarae/login/controller/LoginController.java
- src/main/java/weavers/siltarae/login/domain/RefreshToken.java
- src/main/java/weavers/siltarae/login/domain/TokenProvider.java
- src/main/java/weavers/siltarae/login/domain/repository/RefreshTokenRepository.java
- src/main/java/weavers/siltarae/login/service/LoginService.java
close #68 
- 로그아웃 시, 사용자의 리프레시 토큰을 삭제합니다.
- 액세스 토큰은 클라이언트 측에서 삭제합니다.
- 기존 코드 수정: 액세스 토큰 재발급 실패 시, **사용자 로그아웃 처리 후 예외를 발생**시킵니다.
> feat: [#68]로그아웃 기능 구현

- src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java
- src/main/java/weavers/siltarae/tag/service/TagService.java
- src/test/java/weavers/siltarae/tag/service/TagServiceTest.java
Issue: #52 
- 태그 조회 시 빈 태그 리스트 반환
- deleteAtIsNotNull 을 deleteAtIsNull 로 수정
> fix:[#52] 태그 조회 시 빈 태그 리스트 반환 

- src/main/java/weavers/siltarae/mistake/dto/response/MistakeResponse.java
- src/main/java/weavers/siltarae/tag/dto/response/MistakeTagResponse.java
Issue: #70 
- 태그 조회와 실수 조회 Response Dto 분리
> refactor:[#70] 태그 조회와 실수 조회 Response Dto 분리

- src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
- src/main/java/weavers/siltarae/login/AccessTokenExtractor.java
- src/main/java/weavers/siltarae/login/Auth.java
- src/main/java/weavers/siltarae/login/AuthArgumentResolver.java
- src/main/java/weavers/siltarae/login/service/LoginService.java
close #34 
- 파라미터 어노테이션 **`@Auth`를 추가**하였습니다.
- 컨트롤러 파라미터로 `@Auth` 어노테이션이 붙은 Long 타입의 변수가 있으면, Authorization 헤더에서 memberId를 추출하여 파라미터에 넣어주는 **ArgumentResolver를 추가**하였습니다.
- 헤더에서 액세스 토큰 값을 추출하는 것이 LoginService의 역할과 맞지 않다고 생각하여 **AccessTokenExtractor로 분리**하였습니다.
- 헤더에서 액세스 토큰을 추출하는 부분을 AccessTokenExtractor로 분리하는 것이 적절한 선택이었을까요?
- ArgumentResolver에서 별도의 Exception을 던지고 있지 않습니다. 
`getNativeRequest()`는 스펙 상 Null을 리턴하지 않으며, 그 외에는 파라미터로 잘못된 값이 들어온 경우 해당 메서드에서 예외를 던지기 때문입니다. 이 부분에 대해 예외처리가 적절히 이루어졌는지, 혹시 빼먹은 부분은 없는지 한번 더 확인주시면 감사하겠습니다🙌
> feat: [#34]Authorization 헤더 추출 어노테이션 구현

- src/main/java/weavers/siltarae/comment/controller/CommentController.java
- src/main/java/weavers/siltarae/like/controller/LikeController.java
- src/main/java/weavers/siltarae/login/controller/LoginController.java
- src/main/java/weavers/siltarae/mistake/controller/MistakeController.java
- src/main/java/weavers/siltarae/tag/controller/TagController.java
close #85 
- 컨트롤러의 회원 전용 기능 메서드에 Auth Long memberId 파라미터를 추가했습니다.
- Auth 어노테이션은 액세스 토큰 검증의 역할도 겸하고 있기 때문에, memberId를 사용하지 않더라도 회원 전용 기능이면 Auth 어노테이션을 사용했습니다.
> feat: [#85]회원정보 추출 어노테이션 적용

- src/main/java/weavers/siltarae/comment/controller/CommentController.java
- src/main/java/weavers/siltarae/like/controller/LikeController.java
- src/main/java/weavers/siltarae/login/controller/LoginController.java
- src/main/java/weavers/siltarae/mistake/controller/MistakeController.java
- src/main/java/weavers/siltarae/tag/controller/TagController.java
- src/main/java/weavers/siltarae/tag/service/TagService.java
close #86 
- 태그 삭제 전 본인이 생성한 태그인지 확인하는 로직을 추가했습니다.
- 만약 타인이 생성한 태그가 포함되어 있다면, `NOT_FOUND_TAG`를 반환합니다.
> feat: [#86]태그 삭제 전 본인의 태그인지 확인하는 로직 추가

- src/main/java/weavers/siltarae/login/controller/LoginController.java
close #93 
- 로그인 API를 POST로 변경했어요.
- 구글의 인증 코드를 쿼리가 아닌 바디에서 받아오기로 했어요.
> refactor: [#93]로그인 API를 POST로 변경

- src/main/java/weavers/siltarae/member/controller/MemberController.java
- src/main/java/weavers/siltarae/member/domain/Member.java
- src/main/java/weavers/siltarae/member/service/MemberService.java
close #87 
- 회원 탈퇴 기능이 추가되었어요.
- 회원 탈퇴 시, 회원의 실수와 태그는 그대로 남아요.
- 탈퇴된 회원의 소셜 식별자, 소셜 타입, 이메일은 탈퇴 즉시 파기되고, 닉네임은 `탈퇴회원`으로 변경돼요.
> feat: [#87]회원 탈퇴 기능 추가

- src/main/java/weavers/siltarae/member/controller/MemberController.java
- src/main/java/weavers/siltarae/member/domain/repository/MemberRepository.java
- src/main/java/weavers/siltarae/member/service/MemberService.java
close #106 
- 회원을 조회할 때, 탈퇴 회원 여부를 검사하도록 만들었어요.
- 회원 탈퇴 시, 리프레시 토큰을 삭제하는 로직을 추가했어요.
> feat: [#106]회원 탈퇴 시 토큰 삭제 로직 추가

- src/main/java/weavers/siltarae/mistake/service/MistakeService.java
Issue: #110 
- tag 가 null 이 아니라 비어있어도 오류가 발생하지않고 response 값이 정상적으로 나올 수 있게끔 변경
> fix: [#110] 실수 조회 시 tag 가 null 이 아닌 비어있다면 오류 발생

- src/main/java/weavers/siltarae/member/controller/MemberController.java
- src/main/java/weavers/siltarae/member/dto/request/MemberUpdateRequest.java
- src/main/java/weavers/siltarae/member/dto/response/MemberInfoResponse.java
- src/main/java/weavers/siltarae/member/dto/response/MemberNicknameResponse.java
- src/main/java/weavers/siltarae/member/service/MemberService.java
close #109 
- 회원 정보 조회 기능을 구현했어요.
- RequestDTO와 ResponseDTO의 패키지를 분리했어요.
- 회원 정보에는 닉네임과 프로필 이미지 url이 담겨있어요.
> feat: [#109] 회원정보 조회 기능 구현

- src/main/java/weavers/siltarae/tag/controller/TagController.java
- src/main/java/weavers/siltarae/tag/service/TagService.java
close: #116 
- 태그 등록 API의 응답코드를 204에서 200으로 변경했어요.
- ResponseBody에는 TagResponse(태그 아이디, 태그명, 실수 개수)가 들어있어요.
> refactor: [#116]태그 등록 시 태그정보 반환

- src/main/java/weavers/siltarae/login/AccessTokenExtractor.java
#120 
- 디버깅을 위해 액세스 토큰 추출 시, Authorization Header의 값을 로그로 찍어봤어요.
> fix: [#120]액세스 토큰 추출 로그 추가

- src/main/java/weavers/siltarae/mistake/dto/response/MistakeResponse.java
Issue: #117 
- 실수 조회 시 회원의 정보 포함하여 반환
> refactor: [#117] 실수 조회 시 회원의 정보 포함하여 반환

- src/main/java/weavers/siltarae/tag/domain/Tag.java
close #141 
생성자에서 Tag.mistakes 필드에 새 리스트를 할당해주었어요.
> fix: [#141] 생성자에서 Tag.mistakes 필드 초기화

- src/main/java/weavers/siltarae/member/controller/MemberController.java
- src/main/java/weavers/siltarae/member/dto/response/MemberImageResponse.java
- src/main/java/weavers/siltarae/member/service/MemberService.java
close #147 
프로필 이미지 삭제 API를 추가했어요. 이제 사용자는 기본 이미지로 되돌아갈 수 있어요.
> feat: [#147] 프로필 이미지 삭제 API 추가

- src/main/java/weavers/siltarae/global/image/ImageUtil.java
- src/main/java/weavers/siltarae/global/image/domain/Image.java
- src/main/java/weavers/siltarae/member/controller/MemberController.java
- src/main/java/weavers/siltarae/member/domain/Member.java
- src/main/java/weavers/siltarae/member/service/MemberService.java
close #148 
- 프로필 이미지 업로드를 프로필 이미지 업데이트로 변경했어요. 이미지 파일이 없으면, 프로필 이미지를 기본 이미지로 변경해요. 이미지 업로드 중 에러가 발생하면, 예외 코드를 리턴해요.
- 업로드한 파일이 비어있는지 검증하는 로직과, 이미지 파일인지 검증하는 로직을 별도의 메서드로 분리했어요.
- 파일의 확장자가 제대로 추출되지 않는 버그를 수정했어요.
- `MemberService.updateMemberImage()`에서 이미 빈 파일인지 검사했어요. 그런데 `Image` 클래스에서 또 빈 파일인지 검사할 필요가 있을까요? 저는 클래스의 책임이나, 다른 이미지 업로드 기능을 생각하면 이미지 클래스에서도 검사하는 게 맞을 것 같은데 여기서는 불필요하게 두 번 검사하는게 아닌가 싶어서요. (이래서 null을 하나의 상태로 쓰고 싶지 않았어요..🥲)
- `null`을 하나의 상태로 간주해서 컨트롤러 매개변수로 file이 들어오면 프로필 이미지를 업데이트하고, 그렇지 않으면 기본 이미지로 설정하는 로직으로 구성했어요. 괜찮을까요?🤔
> refactor: [#148] 프로필 이미지 관련 기능 리팩토링

- src/main/java/weavers/siltarae/comment/domain/repository/CommentRepository.java
- src/main/java/weavers/siltarae/comment/service/CommentService.java
- src/main/java/weavers/siltarae/like/service/LikeService.java
- src/main/java/weavers/siltarae/mistake/domain/repository/MistakeRepository.java
- src/main/java/weavers/siltarae/mistake/service/MistakeService.java
Issue: Close #139 
- getTestUser 의 메소드를 getMemberFromId 로 메소드명을 변경해주었습니다.
- Member 객체를 이용하여 조회하는 부분을 MemberId 를 이용하여 조회하는 것으로 변경해주었습니다. 이유는 이미 토큰을 활용해서 회원을 검증하는 데 DB 조회를 이용하여 다시 한번 회원을 검증하는 것을 이중으로 할 필요가 없다고 판단하였습니다.
> refactor: [#139] Test 유저 가져오는 것 실제 Member 로 변경

- src/main/java/weavers/siltarae/mistake/controller/FeedController.java
- src/main/java/weavers/siltarae/mistake/domain/Mistake.java
- src/main/java/weavers/siltarae/mistake/dto/response/FeedListResponse.java
- src/main/java/weavers/siltarae/mistake/dto/response/FeedResponse.java
- src/main/java/weavers/siltarae/mistake/dto/response/MistakeResponse.java
Issue: #138 
- 기존에는 실수와 피드 목록에서 삭제된 댓글도 카운팅 되서 반환되었지만 이 부분을 삭제된 댓글은 카운팅 되지 않게끔 수정하였습니다
> fix: [#138] 실수와 피드 목록에서 삭제된 댓글도 카운팅 되서 반환되는 것 수정

- src/main/java/weavers/siltarae/global/config/CorsConfig.java
Issue: #158 
- https://localhost 으로 들어오는 요청도 허용하였습니다
- 구글 로그인 진행 중에 https 가 아니면 리프레쉬 토큰을 받아올 수 없어서 테스트 환경에서도 https 를 적용하였기에 서버에서도 https 를 허용하기로 하였습니다
> refactor: [#158] https://localhost 요청 허용

- src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
- src/main/java/weavers/siltarae/mistake/controller/FeedController.java
- src/main/java/weavers/siltarae/mistake/service/FeedService.java
- src/main/java/weavers/siltarae/mistake/service/MistakeService.java
- src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java
close #105 
- `getMistakeList()`에서 던지는 예외 코드를 세분화했어요. 이제 태그 리스트로 실수를 조회할 때 삭제된 태그로 조회했는지, 아니면 다른 멤버의 태그로 조회했는지 구분할 수 있어요.
- `getLongs()`, `validateTag()` 메서드를 해체함으로써 호출 depth를 줄였어요. `validateTag()`는 검증 메서드를 호출하는 것 외에 별다른 책임이 없어서 해체하기로 결정했어요 👐 
- 사소한 내용이지만 메서드명 `getfeedList()`를 `getFeedList()`로 카멜 케이스에 맞게 변경했어요 👀
> refactor: getMistakeList() 메서드 개선

- src/main/java/weavers/siltarae/login/AccessTokenExtractor.java
- src/main/java/weavers/siltarae/login/Auth.java
- src/main/java/weavers/siltarae/login/AuthArgumentResolver.java
close #163 
- `@Auth` 어노테이션에 필수여부를 의미하는 `required` 속성을 추가했어요. 기본값은 true에요.
- 만약 `@Auth(required = false)`이고 HTTP Request에 Authorization 헤더가 존재하지 않으면, 컨트롤러 파라미터로 null을 넘겨요.
- 사소한 내용이지만 `AccessTokenExtractor` 클래스에 있던 로그를 삭제했어요 👀
> feat: [#163] @Auth 어노테이션 필수여부 속성 및 관련 로직 추가

- src/main/java/weavers/siltarae/comment/dto/response/CommentResponse.java
- src/main/java/weavers/siltarae/mistake/dto/response/FeedResponse.java
Issue: #169 
- 댓글 목록 조회 시 회원의 이미지 정보를 추가하였습니다.
- 피드 목록 조회 시 회원의 이미지 정보를 추가하였습니다.
> refactor: [#169] 댓글목록 및 피드목록 Response 에 회원의 이미지 정보 추가

- src/main/java/weavers/siltarae/mistake/domain/Mistake.java
- src/main/java/weavers/siltarae/tag/domain/Tag.java
close #178 
- `tag_mistake` 테이블명을 `mistake_tag`로 변경했어요.
- `(tag_id, mistake_id)` 순서로 걸려있던 인덱스를 `(mistake_id, tag_id)` 순서로 변경했어요.
> refactor: [#178] 다대다 연관관계 테이블 복합키 순서 변경

- src/main/java/weavers/siltarae/login/domain/TokenProvider.java
- src/main/java/weavers/siltarae/login/service/LoginService.java
close #188 
- 기존에는 액세스 토큰 재발급 시, 회원 정보를 액세스 토큰에서 불러오고 있었어요.
- 하지만 액세스 토큰을 재발급한다는 건 액세스 토큰이 만료되었다는 의미이기 때문에, Exception이 발생할 가능성이 있어요.
- 그래서 회원 정보를 리프레시 토큰을 통해 조회하도록 로직을 변경했어요.
- `LoginService.login()` 메서드에서 불필요한 파라미터 `socialType`을 제거했어요. 원래는 카카오 로그인이 추가될 때를 대비해서 만들어두었는데, 카카오 로그인을 구현하지 않게 되어 삭제했어요.
> refactor: [#188] 액세스 토큰 재발급 로직 수정

- src/main/java/weavers/siltarae/global/image/domain/Image.java
- src/main/java/weavers/siltarae/mistake/domain/repository/MistakeRepository.java
- src/main/java/weavers/siltarae/tag/dto/response/TagListResponse.java
- src/main/java/weavers/siltarae/tag/dto/response/TagResponse.java
- src/main/java/weavers/siltarae/tag/service/TagService.java
close #168 
- 기존에는 `tag.mistakes.size()`를 통해 태그에 속한 실수 개수를 카운트하고 있었어요. 저희는 soft delete 전략을 채택하고 있었기 때문에, 삭제된 실수의 개수까지 포함되어 카운팅되는 문제가 발생했어요.
- 그래서 ResponseDTO 생성 시 태그에 속한 실수 개수는 별도의 쿼리로 조회한 값을 넣어주기로 했어요. `MistakeRepository.countByTags_IdAndDeletedAtIsNull(Long tagId)` 메서드를 추가하고, 이를 이용해 삭제된 실수는 카운팅에서 제외했어요.
- 사소한 부분이지만, `Image` 클래스에서 사용되지 않던 패키지(Slf4j)를 unimport 했어요.
기존에는 `TagListReponse`에서 `Tag` 엔티티에 의존했는데, 지금은 `TagListResponse` -> `TagResponse` -> `Tag` 순으로 의존하고 있어요. ResponseDTO가 다른 ResponseDTO에 의존하는 게 괜찮을까? 싶은 생각이 들어요🤔
> refactor: [#168] 태그에 속한 실수 개수 카운트 시, 삭제된 실수 필터링 추가

- src/main/java/weavers/siltarae/login/AuthArgumentResolver.java
- src/main/java/weavers/siltarae/login/controller/LoginController.java
- src/main/java/weavers/siltarae/login/domain/LoginInfo.java
- src/main/java/weavers/siltarae/login/domain/TokenPair.java
- src/main/java/weavers/siltarae/login/dto/response/LoginResponse.java
- src/main/java/weavers/siltarae/login/infrastructure/GoogleAuthClient.java
- src/main/java/weavers/siltarae/login/infrastructure/GoogleProvider.java
- src/main/java/weavers/siltarae/login/infrastructure/OAuthProvider.java
- src/main/java/weavers/siltarae/login/infrastructure/TokenProvider.java
- src/main/java/weavers/siltarae/login/service/LoginService.java
- src/main/java/weavers/siltarae/member/service/MemberService.java
- src/test/java/weavers/siltarae/global/ControllerTest.java
- src/test/java/weavers/siltarae/integration/BaseIntegrationTest.java
close #194 
- 기존에는 로그인 성공 시, 액세스 토큰과 리프레시 토큰만 응답했어요.
- 로그인 성공 시, 토큰 값들과 회원 정보(회원 id, 닉네임, 프로필 이미지)를 함께 반환하도록 수정했어요. 
- LoginInfo: 토큰 정보와 회원 정보를 함께 담아 컨트롤러에게 전달하는 클래스
- LoginResponse: 토큰 정보와 회원 정보를 클라이언트 측에 전달하는 DTO
- GoogleProvider, TokenProvider 등 소셜 로그인 관련 제공자들의 패키지를 분리했어요.
- 로그인 성공 시 응답에 토큰 정보와 회원 정보를 함께 반환하는 것 vs 로그인 성공 후 별도로 회원 정보를 조회하는 것. 둘 중에 어떤게 더 나을까 고민이 돼요. 후자는 프론트에서 로그인 시 API를 2번 보내는 방식이라 지금은 일단 1번을 선택했어요.
- 중간에 LoginInfo 클래스가 생성되면서 구조가 조금 복잡해졌는데 괜찮을까요?
- LoginService는 `TokenProvider로부터 받아온 토큰 값` + `MemberRepository로 조회한 회원 정보`를 LoginInfo 객체에 담아 LoginController로 전달해요.
- 그럼 컨트롤러는 다시 LoginInfo에 담긴 값들을 빼내서 쿠키를 설정하고, 응답 body에 필요한 값을 넣어주는 방식이에요.
- 패키지 구조가 이게 최선일까? 싶은 생각이 들어요. `login.infrastructure` 패키지에 다양한 Provider들을 넣고, `login.domain`에는 내부에서 사용하는 데이터 전달용 클래스들만 남겨두었는데... …
> refactor: [#194] 로그인 성공 시, 토큰 정보와 회원 정보를 함께 반환하도록 수정

- src/main/java/weavers/siltarae/login/controller/LoginController.java
close #197 
- 로그아웃 시 리프레시 토큰 쿠키를 삭제하는 로직을 추가했어요.
> fix: [#197] 로그아웃 시 리프레시 토큰 쿠키 삭제 로직 추가

- src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java
- src/main/java/weavers/siltarae/tag/service/TagService.java
- src/test/java/weavers/siltarae/tag/service/TagServiceTest.java
close #199 
- 태그명 중복 검사 시, 삭제된 태그는 중복 검사 대상에서 제외했어요.
- 이제 삭제된 태그와 겹치는 이름의 새로운 태그를 개설할 수 있어요!
> fix: [#199] 태그명 중복 검사 조건 수정

- src/main/java/weavers/siltarae/comment/service/CommentService.java
Issue:  #201 
- 댓글 등록 Response 에 memberImageUrl 값을 추가했습니다.
> fix: 댓글 등록 Response 에 memberImageUrl 추가
